---
version: 0.2

phases:
  pre_build:
    commands:
      - "yum install docker -y"
      - "service docker start"
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 351552566849.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - "echo Build started on `date`"
      - "echo Building the Docker image..."
      - "docker build -t code-pipeline-repo ."
      - "docker tag code-pipeline-repo:latest 351552566849.dkr.ecr.ap-south-1.amazonaws.com/code-pipeline-repo:latest"
  post_build:
    commands:
      - "echo Build completed on `date`"
      - "echo Pushing the Docker image..."
      - "docker push 351552566849.dkr.ecr.ap-south-1.amazonaws.com/code-pipeline-repo:latest"
      - printf '[{"name":"neo-user-container","imageUri":"%s"}]' 351552566849.dkr.ecr.ap-south-1.amazonaws.com/code-pipeline-repo:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json